/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LorientBuildings.glb --transform 
Files: LorientBuildings.glb [883.08KB] > D:\projects\Threejs\r3f-vite-starter\public\models\LorientBuildings-transformed.glb [355.16KB] (60%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshBasicMaterial } from 'three'

export function LorientBuildings(props) {
  const meshBasic = new MeshBasicMaterial({color:'#909090'})

  const { nodes, materials } = useGLTF('/models/LorientBuildings.glb')
  console.log('nodes:', nodes)
  console.log('materials:', materials)

  return (
    <group {...props} dispose={null}>
      {/* <lineSegments geometry={nodes.batiArrettes.geometry} material={nodes.batiArrettes.material} />
      <mesh geometry={nodes.Bati.geometry} material={meshBasic} /> */}
      <mesh geometry={nodes.Activity.geometry} material={meshBasic} />
    </group>
  )
}

useGLTF.preload('/models/LorientBuildings.glb')
