/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LorientBackGround.glb --transform 
Files: LorientBackGround.glb [2.17KB] > D:\projects\Models\school\LorientBackGround-transformed.glb [1.13KB] (48%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshBasicMaterial } from 'three'

export function LorientBackGround(props) {
  const meshBasic = new MeshBasicMaterial({color:'blue'})

  const { nodes, materials } = useGLTF('/models/LorientBackGround-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.backGround.geometry} material={meshBasic} />
    </group>
  )
}

useGLTF.preload('/models/LorientBackGround-transformed.glb')
