/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LorientGround.glb --transform 
Files: LorientGround.glb [466KB] > D:\projects\Threejs\r3f-vite-starter\public\models\LorientGround-transformed.glb [182.36KB] (61%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshBasicMaterial } from 'three'

export function LorientGround(props) {
  const meshBasic = new MeshBasicMaterial({color:'blue'})

  const { nodes, materials } = useGLTF('/models/LorientGround-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.publicParvis.geometry} material={nodes.publicParvis.material} />
      <mesh geometry={nodes.publicWalkway.geometry} material={meshBasic} />
    </group>
  )
}

useGLTF.preload('/models/LorientGround-transformed.glb')
