/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LorientPeople.glb --transform 
Files: LorientPeople.glb [13.82MB] > D:\projects\Threejs\r3f-vite-starter\public\models\LorientPeople-transformed.glb [419.56KB] (97%)
*/

import React, { useRef } from 'react'
import { MeshBasicMaterial } from 'three'
import { useGLTF } from '@react-three/drei'

export function LorientPeople(props) {
  const meshBasic = new MeshBasicMaterial({color:'white'})

  const { nodes, materials } = useGLTF('/models/LorientPeople-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mergedPeople_1.geometry} material={nodes.mergedPeople_1.material} />
      <lineSegments geometry={nodes.mergedPeople_2.geometry} material={meshBasic} />
    </group>
  )
}

useGLTF.preload('/models/LorientPeople-transformed.glb')
