/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LorientSchema.glb --transform 
Files: LorientSchema.glb [52.58KB] > D:\projects\Threejs\r3f-vite-starter\public\models\LorientSchema-transformed.glb [6.94KB] (87%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshBasicMaterial } from 'three'

export function LorientSchema(props) {
  const meshBasic = new MeshBasicMaterial({color:'yellow'})

  const { nodes, materials } = useGLTF('/models/LorientSchema-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.housesGround.geometry} material={nodes.housesGround.material} />
      <mesh geometry={nodes.meshSquare.geometry} material={meshBasic} />
    </group>
  )
}

useGLTF.preload('/models/LorientSchema-transformed.glb')
