/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 LorientTrees.glb --transform 
Files: LorientTrees.glb [16.85MB] > D:\projects\Threejs\r3f-vite-starter\public\models\LorientTrees-transformed.glb [711.04KB] (96%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshBasicMaterial } from 'three'

export function LorientTrees(props) {
  const { nodes, materials } = useGLTF('/models/LorientTrees.glb')
  console.log("nodes:", nodes)
  console.log("materials:", materials)
  const materialBasic = new MeshBasicMaterial({ color: "#6c6960" })
  return (
    <group {...props} dispose={null}>
      <lineSegments geometry={nodes.mergedFoliage.geometry} material={nodes.mergedFoliage.material} />
      <mesh geometry={nodes.mergedTrunks.geometry} material={materialBasic} />
    </group>
  )
}

useGLTF.preload('/models/LorientTrees.glb')
